### PR TITLE
added issue template regarding bug report

### PR DESCRIPTION
**Pull request by MukulsinghRajpurohit**
fixed issue #3

# **Pull request template for the-browser-toolbox/usage-monitor.**
## Description
 *Describe your changes in detail.*
   added issue template on bug report .
   added step to follow.
   and more 

## Related Issue
 *Please link to the related issue here.*
 #3 

## Proposed Changes:
   1.  Change 1
   1.  Change 2
   
# Checklist
- [ ] Test
- [ ] Translations
- [ ] Documentations

## How Has This Been Tested?
 *Please describe in detail how you tested your changes, including details of your testing environment.

## Motivation and Context
 *Why is this change required? What problem does it solve?*
 *If it fixes an open issue, please link to the issue here.*

# Screenshots
Original              |  Updated
:-------------------------: | :-------------------------:
**Original Screenshot**     | **Updated Screenshot**

## Additional Info
 *Any additional info regarding this PR.*

Please use the [Gitter](https://gitter.im/the-browser-toolbox/community) channel to update about your pull request.

### CODE REVIEW

**Comment by MukulsinghRajpurohit** [comment]
is this ok or something

**Comment by adityabisoi** [comment]
The path is okay, but you can find better templates on the internet.

**Comment by MukulsinghRajpurohit** [comment]
## Describe the bug
    A clear and concise description of what the bug is.to

## Step to Reproduce
     Steps to reproduce the behavior :
     1.  Go to '...' 
     2.  Click on '...'
     3.  See error
 
##  What do you believe the expected behavior is
      A clear and concise description of what you expected to happen.

## Relevant Screenshots
   If applicable, add screenshots to help explain your problem.

## Platform details
  where is this occurring and more details about the environment (computer setup) of the customer.
 
**Desktop (please complete the following information):**
  - OS : [e.g. iOS]
  - Browser [e.g. chrome, safari]
  - Version [e.g. 22 or web app]
  
**Mobile (please complete the following information):**
 - Device : [e.g. iPhone6]
 - OS : [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

## Additional context 
  Add any other context about the problem here.

**Comment by MukulsinghRajpurohit** [comment]
is this seems to be better . if any changes needed i will grateful to do it  or if ok can edit the PR to merge

**Comment by adityabisoi** [comment]
This template seems to be perfect, I merged this PR by mistake but reverted it, so please create a new PR with this new template.

**Pull request merged**
